version: '2'
services:
  redis:
    container_name: unms-redis
    image: redis:3.2.3
    restart: always
    mem_limit: 200000000
    volumes:
      - ${DATA_DIR}/redis:/data/db
    ports:
      - 6379:6379
    command: "redis-server --appendonly yes --dir /data/db/"

  mongo:
    container_name: unms-mongo
    image: mongo:3.2.11
    restart: always
    mem_limit: 200000000
    volumes:
      - ${DATA_DIR}/mongo:/data/db
    ports:
      - 27017:27017

  unms:
    container_name: unms
    image: ${DOCKER_IMAGE}:${VERSION}
    restart: always
    mem_limit: 550000000
    depends_on:
      - redis
      - mongo
    volumes:
      - ${DATA_DIR}/cert:/home/app/unms/cert
      - ${DATA_DIR}/images:/home/app/unms/public/site-images
      - ${DATA_DIR}/config-backups:/home/app/unms/data/config-backups
      - ${DATA_DIR}/unms-backups:/home/app/unms/data/unms-backups
    ports:
      - 80:8080
      - 443:8443
    environment:
      - PROD=${PROD}
      - PUBLIC_HTTPS_PORT=443
      - DEMO=${DEMO}
